# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b08b4b855925dc9dd952800d7b3a76bb10ffcf892b8f2c9582ad08148d54273e18dd09d69d4355ca48ea229a1dac3fde7f98c760cceaaf9e1f1d22efd8da626

test:
  secret_key_base: e88aad17940828708fb5141596f85e79039f86f468014f42e02f8e458b4860c71ca318d044bfeb4acb7b70aa4a17f584723657345d0063de2603c9bc949c02d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
